version: '3.8'

services:
  habiny-home:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: habiny-home-nginx
    ports:
      - "80:80"
    volumes:
      # 開発時にソースファイルをリアルタイムで反映
      - ./src:/usr/share/nginx/html:ro
      # nginxログを外部に出力
      - ./logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - habiny-network

  # 開発用: nginxのコンフィグを変更した時に再起動しやすくするためのサービス
  nginx-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: habiny-home-dev
    ports:
      - "3333:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    profiles:
      - dev
    networks:
      - habiny-network

networks:
  habiny-network:
    driver: bridge

volumes:
  nginx_logs:
